modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/cassiancc/Raspberry-Core/issues"
license = "MIT"

[[mods]]
modId = "raspberry"
version = "${version}"
displayName = "Raspberry Core"
authors = "cassiancc, DavigJ"
credits = "Features textures by Derb, n√∂elle, and noodleman, ideas/textures from raspmary. Contains some code from MerchantPug and from the Oreganized mod under MIT License."
description = '''
A collection of compatibility blocks, minor features, and fixes designed for the Raspberry Flavoured modpack.
'''
logoFile = "logo.png"

[[dependencies.raspberry]]
modId = "forge"
mandatory = true
versionRange = "[43.4.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.raspberry]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.19.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.raspberry]]
modId = "farmersdelight"
mandatory = true
versionRange = "[1.19.2-1.2.4,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.raspberry]]
modId = "blueprint"
mandatory = true
versionRange = "[6.2.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.raspberry]]
modId = "supplementaries"
mandatory = true
versionRange = "[1.19.2-2.4.20,)"
ordering = "AFTER"
side = "BOTH"